import Head from "next/head"
import AthletsNormal from "../components/Athlets/"
import PlayersNormal from "../components/Players/"

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AthletsNormal />
        <PlayersNormal />
      </main>
    </>
  )
}

export default Home
