import Head from "next/head"
import AthletsNormal from "../components/Athlets/normal/"
import PlayersNormal from "../components/Players/normal/"
import AthletsMobile from "../components/Athlets/mobile/"
import PlayersMobile from "../components/Players/mobile/"
import useMediaQuery from "@mui/material/useMediaQuery"

function Home() {
  const isMobile = useMediaQuery("(max-width:640px)")

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isMobile ? (
          <>
            <AthletsMobile />
            <PlayersMobile />
          </>
        ) : (
          <>
            <AthletsNormal />
            <PlayersNormal />
          </>
        )}
      </main>
    </>
  )
}

export default Home
